==15510== Memcheck, a memory error detector
==15510== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15510== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==15510== Command: ./target/debug/examples/z_get
==15510== 
[2023-12-14T15:41:23Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 2, id: 0, parent: 255
[2023-12-14T15:41:23Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 3, id: 2, parent: 1
[2023-12-14T15:41:23Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 2, id: 1, parent: 255
[2023-12-14T15:41:24Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 4, id: 4, parent: 255
[2023-12-14T15:41:25Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 4, id: 255, parent: 255
[2023-12-14T15:41:28Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 4, id: 3, parent: 255
[2023-12-14T15:41:28Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 3, id: 6, parent: 255
[2023-12-14T15:41:28Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 2, id: 7, parent: 5
[2023-12-14T15:41:28Z ERROR zenoh::net::runtime] Runtime::drop() - Arc count: 1, id: 5, parent: 4
==15510== 
==15510== HEAP SUMMARY:
==15510==     in use at exit: 60,754,509 bytes in 85,149 blocks
==15510==   total heap usage: 202,852 allocs, 117,703 frees, 119,012,781 bytes allocated
==15510== 
==15510== 96 bytes in 3 blocks are possibly lost in loss record 56 of 213
==15510==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0x7EE9BC: alloc (alloc.rs:102)
==15510==    by 0x7EE9BC: alloc::alloc::Global::alloc_impl (alloc.rs:185)
==15510==    by 0x7EE6F6: alloc::alloc::exchange_malloc (alloc.rs:245)
==15510==    by 0x76ED63: new<alloc::sync::ArcInner<async_io::driver::block_on::{closure_env#1}<core::result::Result<(), async_channel::RecvError>, async_executor::{impl#11}::run::{async_fn_env#0}<core::result::Result<(), async_channel::RecvError>, async_std::task::builder::SupportTaskLocals<async_executor::{impl#5}::run::{async_fn_env#0}<core::result::Result<(), async_channel::RecvError>, async_channel::Recv<()>>>>>>> (boxed.rs:217)
==15510==    by 0x76ED63: alloc::sync::Arc<T>::new (sync.rs:369)
==15510==    by 0x91F9B6: waker_fn::waker_fn (lib.rs:29)
==15510==    by 0x8C5328: async_io::driver::block_on (driver.rs:130)
==15510==    by 0x9216BF: async_global_executor::reactor::block_on::{{closure}} (reactor.rs:3)
==15510==    by 0x92139E: async_global_executor::reactor::block_on (reactor.rs:12)
==15510==    by 0x9191CE: async_global_executor::executor::block_on::{{closure}} (executor.rs:26)
==15510==    by 0x8E1F0D: std::thread::local::LocalKey<T>::try_with (local.rs:270)
==15510==    by 0x8DBC9A: std::thread::local::LocalKey<T>::with (local.rs:246)
==15510==    by 0x919116: async_global_executor::executor::block_on (executor.rs:26)
==15510== 
==15510== 120 bytes in 1 blocks are possibly lost in loss record 63 of 213
==15510==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0xDCB3EC: alloc (alloc.rs:102)
==15510==    by 0xDCB3EC: alloc::alloc::Global::alloc_impl (alloc.rs:185)
==15510==    by 0xDCB186: alloc::alloc::exchange_malloc (alloc.rs:245)
==15510==    by 0xDCAECA: new<alloc::sync::ArcInner<event_listener::Inner>> (boxed.rs:217)
==15510==    by 0xDCAECA: alloc::sync::Arc<T>::new (sync.rs:369)
==15510==    by 0xDCC8BC: event_listener::Event::inner (lib.rs:378)
==15510==    by 0xDCC490: event_listener::Event::listen (lib.rs:175)
==15510==    by 0xD63492: async_lock::once_cell::OnceCell<T>::initialize_or_wait::{{closure}} (once_cell.rs:599)
==15510==    by 0xD62A8D: async_lock::once_cell::now_or_never (once_cell.rs:769)
==15510==    by 0xD644DA: async_lock::once_cell::OnceCell<T>::get_or_try_init_blocking (once_cell.rs:428)
==15510==    by 0xD6437E: async_lock::once_cell::OnceCell<T>::get_or_init_blocking (once_cell.rs:491)
==15510==    by 0xD5B90D: async_io::reactor::Reactor::get (reactor.rs:72)
==15510==    by 0xD5B157: async_io::driver::main_loop (driver.rs:52)
==15510== 
==15510== 288 bytes in 1 blocks are possibly lost in loss record 89 of 213
==15510==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0x40147D9: calloc (rtld-malloc.h:44)
==15510==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==15510==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==15510==    by 0x49FD7B4: allocate_stack (allocatestack.c:430)
==15510==    by 0x49FD7B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==15510==    by 0xF296FE: std::sys::unix::thread::Thread::new (thread.rs:87)
==15510==    by 0xCAE346: std::thread::Builder::spawn_unchecked_ (mod.rs:563)
==15510==    by 0xCAD98E: std::thread::Builder::spawn_unchecked (mod.rs:457)
==15510==    by 0xCAF78D: std::thread::Builder::spawn (mod.rs:389)
==15510==    by 0xC9B136: async_global_executor::tokio::RUNTIME::{{closure}}::{{closure}} (tokio.rs:12)
==15510==    by 0xC90293: core::result::Result<T,E>::unwrap_or_else (result.rs:1428)
==15510==    by 0xC9AF39: async_global_executor::tokio::RUNTIME::{{closure}} (tokio.rs:9)
==15510==    by 0xCA8CED: core::ops::function::FnOnce::call_once (function.rs:250)
==15510==    by 0xCA8C3A: core::ops::function::FnOnce::call_once (function.rs:250)
==15510== 
==15510== 288 bytes in 1 blocks are possibly lost in loss record 90 of 213
==15510==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0x40147D9: calloc (rtld-malloc.h:44)
==15510==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==15510==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==15510==    by 0x49FD7B4: allocate_stack (allocatestack.c:430)
==15510==    by 0x49FD7B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==15510==    by 0xF296FE: std::sys::unix::thread::Thread::new (thread.rs:87)
==15510==    by 0xD6C4A8: std::thread::Builder::spawn_unchecked_ (mod.rs:563)
==15510==    by 0xD6BB57: std::thread::Builder::spawn_unchecked (mod.rs:457)
==15510==    by 0xD6CAB6: std::thread::Builder::spawn (mod.rs:389)
==15510==    by 0xD5B060: async_io::driver::unparker::{{closure}} (driver.rs:30)
==15510==    by 0xD643E8: async_lock::once_cell::OnceCell<T>::get_or_init_blocking::{{closure}} (once_cell.rs:492)
==15510==    by 0xD64746: async_lock::once_cell::OnceCell<T>::get_or_try_init_blocking::{{closure}} (once_cell.rs:429)
==15510==    by 0xD63D9F: async_lock::once_cell::OnceCell<T>::initialize_or_wait::{{closure}} (once_cell.rs:626)
==15510==    by 0xD62CCD: async_lock::once_cell::now_or_never (once_cell.rs:769)
==15510== 
==15510== 512 bytes in 16 blocks are possibly lost in loss record 111 of 213
==15510==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0xC9C43C: alloc (alloc.rs:102)
==15510==    by 0xC9C43C: alloc::alloc::Global::alloc_impl (alloc.rs:185)
==15510==    by 0xC9C1D6: alloc::alloc::exchange_malloc (alloc.rs:245)
==15510==    by 0xC9F7C3: new<alloc::sync::ArcInner<async_io::driver::block_on::{closure_env#1}<(), futures_lite::future::Or<async_executor::{impl#11}::run::{async_fn_env#0}<(), async_global_executor::threading::thread_main_loop::{closure#1}::{closure#0}::{async_block_env#0}>, async_executor::{impl#5}::run::{async_fn_env#0}<(), futures_lite::future::Pending<()>>>>>> (boxed.rs:217)
==15510==    by 0xC9F7C3: alloc::sync::Arc<T>::new (sync.rs:369)
==15510==    by 0xC9E436: waker_fn::waker_fn (lib.rs:29)
==15510==    by 0xC94F18: async_io::driver::block_on (driver.rs:130)
==15510==    by 0xCAB4AF: async_global_executor::reactor::block_on::{{closure}} (reactor.rs:3)
==15510==    by 0xCAB038: async_global_executor::reactor::block_on (reactor.rs:12)
==15510==    by 0xCAC2C8: async_global_executor::threading::thread_main_loop::{{closure}}::{{closure}} (threading.rs:95)
==15510==    by 0xC8AB90: std::thread::local::LocalKey<T>::try_with (local.rs:270)
==15510==    by 0xC88773: std::thread::local::LocalKey<T>::with (local.rs:246)
==15510==    by 0xCAC1A4: async_global_executor::threading::thread_main_loop::{{closure}} (threading.rs:89)
==15510== 
==15510== 864 bytes in 3 blocks are possibly lost in loss record 125 of 213
==15510==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0x40147D9: calloc (rtld-malloc.h:44)
==15510==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==15510==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==15510==    by 0x49FD7B4: allocate_stack (allocatestack.c:430)
==15510==    by 0x49FD7B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==15510==    by 0xF296FE: std::sys::unix::thread::Thread::new (thread.rs:87)
==15510==    by 0x8AD327: std::thread::Builder::spawn_unchecked_ (mod.rs:563)
==15510==    by 0x8AC8EE: std::thread::Builder::spawn_unchecked (mod.rs:457)
==15510==    by 0x8AD97D: std::thread::Builder::spawn (mod.rs:389)
==15510==    by 0x778E06: zenoh_transport::manager::TransportExecutor::new (manager.rs:332)
==15510==    by 0x779403: zenoh_transport::manager::TransportManager::new (manager.rs:427)
==15510==    by 0x77855B: zenoh_transport::manager::TransportManagerBuilder::build (manager.rs:291)
==15510==    by 0x248D4C: zenoh::net::runtime::Runtime::init::{{closure}} (mod.rs:209)
==15510==    by 0x23FD6D: zenoh::session::Session::new::{{closure}} (session.rs:845)
==15510== 
==15510== 1,072 bytes in 1 blocks are possibly lost in loss record 127 of 213
==15510==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0xD3284C: alloc (alloc.rs:102)
==15510==    by 0xD3284C: alloc::alloc::Global::alloc_impl (alloc.rs:185)
==15510==    by 0xD33158: <alloc::alloc::Global as core::alloc::Allocator>::allocate (alloc.rs:245)
==15510==    by 0xD36BD7: hashbrown::raw::alloc::inner::do_alloc (alloc.rs:15)
==15510==    by 0xD2705E: hashbrown::raw::RawTableInner<A>::new_uninitialized (mod.rs:1578)
==15510==    by 0xD2765F: hashbrown::raw::RawTableInner<A>::fallible_with_capacity (mod.rs:1614)
==15510==    by 0xD25D2D: hashbrown::raw::RawTableInner<A>::prepare_resize (mod.rs:2156)
==15510==    by 0xCD1878: resize_inner<alloc::alloc::Global> (mod.rs:2229)
==15510==    by 0xCD1878: reserve_rehash_inner<alloc::alloc::Global> (mod.rs:2206)
==15510==    by 0xCD1878: hashbrown::raw::RawTable<T,A>::reserve_rehash (mod.rs:1120)
==15510==    by 0xCD2B4C: hashbrown::raw::RawTable<T,A>::reserve (mod.rs:1086)
==15510==    by 0xCD2154: hashbrown::raw::RawTable<T,A>::find_or_find_insert_slot (mod.rs:1262)
==15510==    by 0xCBCCBD: hashbrown::map::HashMap<K,V,S,A>::insert (map.rs:1750)
==15510==    by 0xCE109A: std::collections::hash::map::HashMap<K,V,S>::insert (map.rs:1103)
==15510== 
==15510== 4,608 bytes in 16 blocks are possibly lost in loss record 147 of 213
==15510==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0x40147D9: calloc (rtld-malloc.h:44)
==15510==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==15510==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==15510==    by 0x49FD7B4: allocate_stack (allocatestack.c:430)
==15510==    by 0x49FD7B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==15510==    by 0xF296FE: std::sys::unix::thread::Thread::new (thread.rs:87)
==15510==    by 0xCF51C7: std::thread::Builder::spawn_unchecked_ (mod.rs:563)
==15510==    by 0xCF478E: std::thread::Builder::spawn_unchecked (mod.rs:457)
==15510==    by 0xCF582D: std::thread::Builder::spawn (mod.rs:389)
==15510==    by 0xCEA7B3: tokio::runtime::blocking::pool::Spawner::spawn_thread (pool.rs:468)
==15510==    by 0xCEA04B: tokio::runtime::blocking::pool::Spawner::spawn_task (pool.rs:418)
==15510==    by 0xCE9B3F: tokio::runtime::blocking::pool::Spawner::spawn_blocking_inner (pool.rs:386)
==15510==    by 0xCE9396: tokio::runtime::blocking::pool::Spawner::spawn_blocking (pool.rs:301)
==15510==    by 0xD1059C: tokio::runtime::handle::Handle::spawn_blocking (handle.rs:219)
==15510== 
==15510== 4,608 bytes in 16 blocks are possibly lost in loss record 148 of 213
==15510==    at 0x484DA83: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==15510==    by 0x40147D9: calloc (rtld-malloc.h:44)
==15510==    by 0x40147D9: allocate_dtv (dl-tls.c:375)
==15510==    by 0x40147D9: _dl_allocate_tls (dl-tls.c:634)
==15510==    by 0x49FD7B4: allocate_stack (allocatestack.c:430)
==15510==    by 0x49FD7B4: pthread_create@@GLIBC_2.34 (pthread_create.c:647)
==15510==    by 0xF296FE: std::sys::unix::thread::Thread::new (thread.rs:87)
==15510==    by 0xCAED49: std::thread::Builder::spawn_unchecked_ (mod.rs:563)
==15510==    by 0xCAD82F: std::thread::Builder::spawn_unchecked (mod.rs:457)
==15510==    by 0xCAF7B1: std::thread::Builder::spawn (mod.rs:389)
==15510==    by 0xCABC48: async_global_executor::threading::spawn_more_threads::{{closure}} (threading.rs:43)
==15510==    by 0xCB0D0B: async_global_executor::init::init::{{closure}} (init.rs:38)
==15510==    by 0xC9789D: async_io::driver::block_on (driver.rs:146)
==15510==    by 0xCAB510: async_global_executor::reactor::block_on::{{closure}} (reactor.rs:3)
==15510==    by 0xCAB3EB: async_global_executor::reactor::block_on (reactor.rs:12)
==15510== 
==15510== LEAK SUMMARY:
==15510==    definitely lost: 0 bytes in 0 blocks
==15510==    indirectly lost: 0 bytes in 0 blocks
==15510==      possibly lost: 12,456 bytes in 58 blocks
==15510==    still reachable: 60,742,053 bytes in 85,091 blocks
==15510==         suppressed: 0 bytes in 0 blocks
==15510== Reachable blocks (those to which a pointer was found) are not shown.
==15510== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==15510== 
==15510== For lists of detected and suppressed errors, rerun with: -s
==15510== ERROR SUMMARY: 9 errors from 9 contexts (suppressed: 0 from 0)
